### ISSUE TITLE
feat: Add inductive types and definitions

### ISSUE THREAD

**Issue by smalewski** [pleiad/GCIC#21]
Add support for non-indexed inductive types:

# Syntax
## Definitions
```
inductive list (a : □0) : □0 =
| nil : list a
| cons : a -> list a -> list a;;
```

## Inductives and constructors

Since we don't have implicit argument yet, inductive types and constructors need to be called with the parameters of the inductive type:
```
list □1
nil □1
cons □1 □0 (nil □1)
```

## Match expressions

```
match nil □1 as z return is_empty z with
| nil _ -> true
| cons _ _ _ -> false
end
```

# Features
- Wildcard patterns
- Constructors are lambdas (like Haskell instead of Ocaml)
- Mutually recursive types are left for a future issue (?).

**Comment by TDiazT** [comment]
Might be useful to check Brady's talk on Idris 2 (https://www.youtube.com/watch?v=mFuh_ilAm5E)
