### ISSUE TITLE
feat: Print declaration signatures after running 'def' command.

### ISSUE THREAD

**Issue by smalewski** [pleiad/GCIC#25]
```
def foo : Type 0;;
```
Should return `foo : Type1` instead of `OK`.

**Comment by etanter** [comment]
done

**Comment by etanter** [comment]
@smalewski @TDiazT I renamed the cmd constructor for def, from `Definition` to `Define` (for consistency with the other constructors, which are verbs)

**Comment by etanter** [comment]
the new `cmd_result` constructor is called `Definition` (consistent with the other constructor names)
